site_name: Learning Logs
docs_dir: content
site_url: https://j-dumas.github.io/learning-logs/
site_description: My journey of learning

theme:
    name: 'material'
    icon:
      logo: material/file-code-outline
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
    - Home: index.md
    - Projects: Projects/

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.superfences

  - toc:
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify

plugins:
  - search
  - roamlinks

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



